# Specify the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app/src

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose a port if your application listens on a specific port (optional)
EXPOSE 3000

# Specify the command to run when the container starts
CMD [ "npm", "start" ]
